
#
# iPixeli's LagMeter Mod 
# Client Configuration File 
# https://www.curseforge.com/minecraft/mc-mods/lagmeter 
#
[GENERAL]
	#singleline: Renders all in a single line.
	singleline = false
	#rendercorner: Where to display on screen.
	#Allowed Values: TOPLEFT, TOPRIGHT, BOTTOMRIGHT, BOTTOMLEFT
	rendercorner = "BOTTOMLEFT"

[INFORMATION]
	#showtps: Allowed Values are true or false
	showtps = true
	#tpsoutdated: How many seconds can pass before the last known TPS value is considered outdated. (Modifiable via file only)
	#Range: 0 ~ 30
	tpsoutdated = 10
	#tpsdata: What TPS data will render on screen.
	#Allowed Values: SERVERONLY, CURRENTWORLD, ALLWORLDS
	tpsdata = "SERVERONLY"

[TEXT]
	#textoutline: Allowed Values are true or false
	textoutline = false
	#textcolorspecific: Will be ignored when textcolordynamic is enabled. Accepts hexadecimal values converted to decimal format. (Modifiable via file only)
	#Range: 0 ~ 16777215
	textcolorspecific = 16777215
	#textshadow: Allowed Values are true or false
	textshadow = false
	#textcolordynamic: Allowed Values are true or false
	textcolordynamic = true

